language: node_js
node_js:
- '12'
- '13'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  edge: true
  email: curt.tudor@netfoundry.io
  api_key:
    secure: lLWwfh37YcPjipWvv2uyK12I6PEshdqnkzVQmD7DMwhmRuyCIuNKDrAnACzdgf3aLWAKJyrNXc0h5PNnR49dZsmzHJ24xFXhYsUyVO5R2pCrK4eBiqBcrlno1gidscCtvZAsEILYDk51/uztcz1aXl4I905CH1oaJcGmSyG1vLGDJiT0O03yd93y6GUt0opRXXp7mGjmToMroRJ6TEy5MWsZ5vZrXBs0wBaSaYCGoG6P/h71+7C2uCdgfoXIH4G2jeSYLkL4lzQlF3ZrQ5XxBiGmrEOsWUhCMMDRSIphpfBH+UVzK++pWw/l9dOQjiz00Dv0H8Tw0ek4wkXHguMA906D+t4njbIcjs0xiNvTPOjLbyG8kStpvJLaeunp3H5PbwShygvxXWIYSIFICN5ukHRKQZgQJpqphaS8q5/LyZZJb0jCUOBMlFXz4JKmKV6xlaXaBkNHiboiqeEJZ2InI21IayziVqyuGDNh566k49Fb7oiCqrvAIGyZKQ9n6Uy4/NxrQpgI4+2ZoBtozk8TTP1pQ7feE3D3KozKeZnFD6yXgczVGwDr8E4jTVj9uYQdjd9xgXyHFiIjSMuABMIifQgIlZ6ZZLF+2I8UGIZvZAk2QKg0QzudvqWBCio0zZzPCMkhHN4CzoQJBuT7uS6yKcmP3f6yJrJJcXl675hbZuw=
  on:
    tags: true
    branch: master
